# Generated by Django 5.1.3 on 2024-12-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('pk_user', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('birthdate', models.DateField(help_text='Fecha nacimiento')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='location.location_model')),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rol.rol_model')),
            ],
        ),
    ]
