# Generated by Django 5.1.3 on 2024-12-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Model',
            fields=[
                ('pk_restaurant', models.AutoField(primary_key=True, serialize=False)),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
                ('company_name', models.CharField(max_length=50, verbose_name='Razon social')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='location.location_model')),
                ('fk_responsible_user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user_model')),
            ],
        ),
    ]
