# Generated by Django 5.1.3 on 2024-12-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential_Model',
            fields=[
                ('pk_credential', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_model')),
            ],
        ),
    ]
