# Generated by Django 5.1.3 on 2024-12-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_In_Place_Model',
            fields=[
                ('pk_delivery_in_place', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=30, verbose_name='Nro. Pedido')),
                ('restaurant_name', models.CharField(max_length=50, verbose_name='Nombre restaurante')),
                ('dish_name', models.CharField(max_length=50, verbose_name='Nombre plato')),
                ('delivery_state', models.CharField(max_length=20, verbose_name='Estado entrega')),
                ('comments', models.CharField(max_length=300, verbose_name='Comentarios')),
                ('fk_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.order_model')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user_model')),
            ],
        ),
    ]
