# Generated by Django 5.1.3 on 2024-11-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog_Model',
            fields=[
                ('pk_catalog', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=50, verbose_name='Nombre restaurante')),
                ('dish_name', models.CharField(max_length=50, verbose_name='Nombre plato')),
            ],
        ),
    ]
