# Generated by Django 5.1.3 on 2024-12-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_Model',
            fields=[
                ('pk_rol', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nombre rol')),
                ('category', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
        ),
    ]
