# Generated by Django 5.1.3 on 2024-12-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('pk_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=30, verbose_name='Nro. Pedido')),
                ('dish_name', models.CharField(max_length=50, verbose_name='Razon social')),
                ('quota_abailable', models.IntegerField(help_text='Cupo disponible')),
                ('qualification', models.IntegerField(help_text='Calificacion')),
                ('dispatch', models.CharField(max_length=100, verbose_name='Despacho (envio/entrega)')),
                ('fk_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish_model')),
                ('fk_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant_model')),
            ],
        ),
    ]
